# Generated by Django 4.1.7 on 2023-04-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0031_comment_cmntreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_emailVerified',
            field=models.BooleanField(default=False),
        ),
    ]
