# Generated by Django 4.1.7 on 2023-04-07 18:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0034_alter_reminder_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="likes",
            field=models.ManyToManyField(
                default=0, related_name="notes_like", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
